apiVersion: v1
kind: PersistentVolume
metadata:
  name: schemes-read-model-connector-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: ml-small-disk
    fsType: ext4
