apiVersion: v1
kind: PersistentVolume
metadata:
  name: schemes-read-model-connector-pv
  labels:
    app: schemes-read-model-connector
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: ml-small-disk-2
    fsType: ext4
