kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: schemes-read-model-connector-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
  # selector:
  #   matchLabels:
  #     app: schemes-read-model-connector
