kind: PersistentVolume
apiVersion: v1
metadata:
  name: schemes-read-model-connector-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: "/mnt/data/connector"
