kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: schemes-connector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
